#!/bin/bash
# ceilometer_third_party_meters daemon
# chkconfig: 345 20 80
# description: ceilometer_third_party_meters daemon
# processname: ceilometer_third_party_meters

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/lib/python2.7/transcirrus/daemons/ceilometer_third_party_meters
NAME=ceilometer_third_party_meters
PIDFILE=/var/run/$NAME.pid
#SCRIPTNAME=/etc/init.d/$NAME

test -e $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
     log_success_msg "Starting Ceilometer Third Party Meters"
     /usr/local/bin/python2.7 /usr/local/lib/python2.7/transcirrus/daemons/daemon_obtain_third_party_meters.py $PIDFILE start
#     start_daemon -p $PIDFILE $DAEMON
#     PID=`ps x |grep '/usr/local/bin/python2.7 /usr/local/lib/python2.7/transcirrus/core/ciac_server.py' | head -1 | awk '{print $1}'`
#     echo $PID > $PIDFILE
   ;;
  stop)
     log_success_msg "Stopping Ceilometer Third Party Meters"
     /usr/local/bin/python2.7 /usr/local/lib/python2.7/transcirrus/daemons/daemon_obtain_third_party_meters.py $PIDFILE stop
#     killproc -p $PIDFILE $DAEMON
#     PID=`ps x |grep '/usr/local/bin/python2.7 /usr/local/lib/python2.7/transcirrus/core/ciac_server.py' | head -1 | awk '{print $1}'`
#     kill -9 $PID
#     log_success_msg $PID
   ;;
  force-reload|restart)
     $0 stop
     $0 start
   ;;
#  status)
#     PID=`ps x |grep '/usr/local/bin/python2.7 /usr/local/lib/python2.7/transcirrus/core/ciac_server.py' | head -1 | awk '{print $1}'`
#     if [[ `pidof -x /usr/local/bin/python2.7 ciac_server.py` -eq $PID ]]; then
#         echo 'Ceilometer Memory Patch is running' $PID
#     else
#         if [[ `pidof -x /usr/local/bin/python2.7 ciac_server.py` -ne $PID ]]; then
#             echo 'Ceilometer Memory Patch is dead'
#         fi
#     fi
#   ;;
 *)
   echo "Usage: /etc/init.d/ceilometer_third_party_meters {start|stop|restart|force-reload}"
   exit 1
  ;;
esac

exit 0