##This file will be written out by values inserted into the system database
#defaults will be factory set
#file will update when local admin sets up system.

#####DO NOT EDIT THIS FILE BY HAND IT WILL BE OVER WRITTEN#####
#node specific settings
NODE_ID="000-12345678-12345"
NODE_NAME="integration"

TRANSCIRRUS_DB="192.168.10.37"
TRAN_DB_USER="transuser"
TRAN_DB_PASS="builder"
TRAN_DB_NAME="transcirrus"
TRAN_DB_PORT="5432"

#change during setup if needed from DB vars
ADMIN_TOKEN="cheapass"
API_IP="192.168.10.37"

#change this, update as neccessary from setup operation
CLOUD_CONTROLLER="integration"
CLOUD_CONTROLLER_ID="000-12345678-12345"
CLOUD_NAME="RegionOne"

#DEFAULT openstack roles
MEMBER_ROLE_ID="6ab6e8bce7eb4277a5feaeff3c2e4abf"
ADMIN_ROLE_ID="db495b7ad9954facafc44970784bf6ae"

##DEFAULT OPENSTACK DB SETTINGS##
OS_DB="192.168.10.37"
OS_DB_PORT="5432"
OS_DB_USER="root"
OS_DB_PASS="builder"

