# This file has the version information for this TransCirrus product.

VERSION_MAJOR = "2"
VERSION_MINOR = "2"
VERSION_RELEASE = "1"
VERSION_FULL_STR = VERSION_MAJOR + "." + VERSION_MINOR + "-" + VERSION_RELEASE
VERSION_SHORT_STR = VERSION_MAJOR + "." + VERSION_MINOR